var dx={};dx.call=function(a,b,d,c){a="/api/?type=json&method="+a+"."+b;for(var e in d)if(d.hasOwnProperty(e))a+="&"+e+"="+d[e];$.ajax({url:a,dataType:"jsonp",success:c})};dx.flash=function(a){var b=a.height/a.width,d=$(".gallerySingle").width();if(a.width>d){a.width=d;a.height=Math.round(d*b)}$(".gallerySingle").flash(a)};
dx.featured=function(){var a=0,b=null,d=null,c=1E3/41,e=function(){var h=(new Date).getTime()-d,k=960-(a*240+Math.floor(240*(h/8E3)));$("#featured").css("background-position","-"+k+"px 100%");if(h>8E3){a++;if(a>=4){$("#featured li:not(:first)").hide();$("#featured li:last").show().fadeOut();a=0}else $("#featured li:eq("+a+")").fadeIn();d=(new Date).getTime()}};(function(){$("#featured").find("li:not(:first)").hide();d=(new Date).getTime();b=setInterval(e,c);$("#featured a").mouseover(function(){clearInterval(b);
d=(new Date).getTime();e()}).mouseout(function(){b=setInterval(e,c);d=(new Date).getTime()})})()};
dx.archives=function(){var a=new Date,b=a.getMonth(),d=a.getFullYear(),c=[31,28,31,30,31,30,31,31,30,31,30,31],e=["January","February","March","April","May","June","July","August","September","October","November","December"],h=function(f){var i,j,g=b+1+"/1/"+d;if(g=Date.parse(g)){g=new Date(g);g.setDate(1);var l=g.getMonth();i=e[l];j=g.getFullYear();l=l===1?j%4===0?29:28:c[l];var o=g.getDay(),m="<table><tbody><tr>",n=0,p=g.getDay();for(g=0;g<p;g++)m+='<td class="noDate">&nbsp;</td>';for(g=0;g<l;g++){n=
g+o;if(n%7===0)m+="</tr>";m+='<td class="day'+(g+1)+'">'+(g+1)+"</td>"}for(n++;n%7!==0;){m+='<td class="noDate">&nbsp;</td>';n++}m+="</tr></tbody></table>";$("#archives div").html(m);$("#archives h3").html(i+" "+j)}if(f.body.content.length>0){i=0;for(j=f.body.content.length;i<j;i++){l=(new Date(f.body.content[i].date*1E3)).getDate();$("td.day"+l).addClass("hasPosts")}}},k=function(){var f=b+1,i=d,j="",g="";if(f>12){f=1;i++}g=f+"/1/"+i;if(f+1>12){f=0;i++}j=f+1+"/1/"+i;dx.call("content","getContent",
{noCount:"true",noTags:"true",maxdate:j,mindate:g,select:"title,perma,date",contentType:"art,video,blog,portfolio"},h)};$("#archives .control").click(function(f){switch($(f.target).attr("rel")){case "prev":b--;break;case "next":b++}if(b<0){b=11;d--}if(b>11){b=0;d++}k()});k();$("#archives").delegate(".hasPosts","click",function(){var f=(b+1).toString();window.location.href="/archives/"+(f.length<2?"0"+f:f)+"/"+d+"/"})};
dx.comments=function(){var a=0,b=0,d=function(c){if(c=$(c.target).attr("rel")){var e=c*30,h=e+30-1;$(".comment").show();$(".comment:gt("+h+")").hide();$(".comment:lt("+e+")").hide();$(".commentPages .selected").removeClass("selected");$('.commentPages [rel="'+c+'"]').addClass("selected")}};$(".commentReply").click(function(c){c=$(c.target).parent().find(".user").text();$("#commentBody").val("@"+c).focus()});(function(){a=$(".commentReply").length;if(a>30){b=Math.ceil(a/30);$(".comment:gt(29)").hide();
var c='<ul class="commentPages">',e;for(e=0;e<b;e++)c+='<li><a href="#comments" class="commentPage'+(e===0?" selected":"")+'" rel="'+e+'">'+(e+1)+"</a></li>";c+="</ul>";$("#comments").append(c);$(c).insertAfter("#comments h3");$(".commentPage").click(d)}})()};
dx.gallery=function(){var a=function(d){d.preventDefault();var c=$(d.target).attr("href");c||(c=$(d.target).parents("a:first").attr("href"));c=c.match(/entry\/(.*?)\//)[1];$("#galleryBg").fadeIn(400,function(){var e=c;$("#galleryItem").prepend('<iframe src="/gallery/'+e+'/" id="galleryItem" frameborder="0"></iframe>')});$("#galleryItem").show().animate({width:"800px"})},b=function(){$("#galleryBg").fadeOut();$("#galleryItem").animate({width:0}).fadeOut();$("#galleryItem iframe").remove()};$(function(){$("#gallery a").click(a);
$("#galleryBg").detach().appendTo("body").click(b);$("#galleryItem").css("margin-top",($(window).height()-$("#galleryItem").height())/2+"px");$("#galleryItem .close").click(b)})};
dx.poll=function(a){var b=$("#poll"+a),d=function(c){if(typeof c.body.items!=="undefined"&&c.body.items.length>0){var e='<div class="graph"><h4>'+c.body.title+"</h4><ul>",h,k;h=0;for(k=c.body.items.length;h<k;h++){var f=c.body.items[h];e+="<li><span>"+f.title+"</span>"+(f.votes>0?'<div class="bar" style="width:'+f.percent/2+'%;"></div>':"")+'<div class="data">'+f.percent+"% - "+f.votes+" votes</div></li>"}e+="</ul></div>";b.replaceWith(e)}};b.submit(function(c){c.preventDefault();c=b.find('input[name="poll_option"]:checked').val();
dx.call("poll","vote",{id:a,item:c},d)})};
(function(){var a=function(){var b=false;$("label.error").removeClass("error");if($("#commentName").length&&!$("#commentName").val()){b=true;$('label[for="commentName"]').addClass("error")}if($("#commentEmail").length&&!$("#commentEmail").val()){b=true;$('label[for="commentEmail"]').addClass("error")}else if($("#commentEmail").length){var d=$("#commentEmail").val();if(d.match(/([\w\d]+)@([\w\d]+)\.([\w])/))$("#botProof").val(hex_md5(d));else b=true}if(!$("#commentBody").val()){b=true;$('label[for="commentBody"]').addClass("error")}return!b};
$(function(){$("#commentForm").submit(a)})})();(function(a){a.fn.video=function(b){this.each(function(){a(this).append('<embed width="610" height="350" src="/global/flash/jcplayer.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" align="middle" play="true" loop="true" scale="noScale" wmode="window" devicefont="false" bgcolor="#ffffff" name="jcplayer" menu="true" allowfullscreen="true" salign="TL" allowscriptaccess="sameDomain" flashvars="videoURL='+b+'&amp;autoHide=true&amp;margins=10&amp;offsetY=35&amp;highlightColor=0xf26716" type="application/x-shockwave-flash" />')})}})(jQuery);
(function(a){a.fn.youtube=function(b){this.each(function(){a(this).append('<embed width="540" height="304" src="http://www.youtube.com/v/'+b+"?enablejsapi=1&playerapiid="+a(this).attr("id")+'" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" align="middle" wmode="window" llowscriptaccess="sameDomain" type="application/x-shockwave-flash" />')})}})(jQuery);
(function(a){var b=function(d){var c=a('#search input[type="text"]').val();if(c.length>0)window.location="/search/"+c+"/";d.preventDefault()};a(function(){a("#search form").submit(b)})})(jQuery);$(function(){$(".gallery a").length>0&&$(".gallery a").lightBox()});