var dx={};dx.call=function(a,b,c,d){a="/api/?type=json&method="+a+"."+b;for(var e in c)if(c.hasOwnProperty(e))a+="&"+e+"="+c[e];$.ajax({url:a,dataType:"jsonp",success:d})};dx.flash=function(a){var b=a.height/a.width,c=$(".gallerySingle").width();if(a.width>c){a.width=c;a.height=Math.round(c*b)}$(".gallerySingle").flash(a)};
dx.featured=function(){var a=0,b=null,c=null,d=1E3/41,e=function(){var k=(new Date).getTime()-c,n=960-(a*240+Math.floor(240*(k/8E3)));$("#featured").css("background-position","-"+n+"px 100%");if(k>8E3){a++;if(a>=4){$("#featured li:not(:first)").hide();$("#featured li:last").show().fadeOut();a=0}else $("#featured li:eq("+a+")").fadeIn();c=(new Date).getTime()}};(function(){$("#featured").find("li:not(:first)").hide();c=(new Date).getTime();b=setInterval(e,d);$("#featured a").mouseover(function(){clearInterval(b);
c=(new Date).getTime();e()}).mouseout(function(){b=setInterval(e,d);c=(new Date).getTime()})})()};
dx.archives=function(){var a=new Date,b=a.getMonth(),c=a.getFullYear(),d=[31,28,31,30,31,30,31,31,30,31,30,31],e=["January","February","March","April","May","June","July","August","September","October","November","December"],k=function(g){var h,i,f=b+1+"/1/"+c;if(f=Date.parse(f)){f=new Date(f);f.setDate(1);var j=f.getMonth();h=e[j];i=f.getFullYear();j=j===1?i%4===0?29:28:d[j];var o=f.getDay(),l="<table><tbody><tr>",m=0,p=f.getDay();for(f=0;f<p;f++)l+='<td class="noDate">&nbsp;</td>';for(f=0;f<j;f++){m=
f+o;if(m%7===0)l+="</tr>";l+='<td class="day'+(f+1)+'">'+(f+1)+"</td>"}for(m++;m%7!==0;){l+='<td class="noDate">&nbsp;</td>';m++}l+="</tr></tbody></table>";$("#archives div").html(l);$("#archives h3").html(h+" "+i)}if(g.body.content.length>0){h=0;for(i=g.body.content.length;h<i;h++){j=(new Date(g.body.content[h].date*1E3)).getDate();$("td.day"+j).addClass("hasPosts")}}},n=function(){var g=b+1,h=c,i="",f="";if(g>12){g=1;h++}f=g+"/1/"+h;if(g+1>12){g=0;h++}i=g+1+"/1/"+h;dx.call("content","getContent",
{noCount:"true",noTags:"true",maxdate:i,mindate:f,select:"title,perma,date",contentType:"art,video,blog,portfolio"},k)};$("#archives .control").click(function(g){switch($(g.target).attr("rel")){case "prev":b--;break;case "next":b++}if(b<0){b=11;c--}if(b>11){b=0;c++}n()});n();$("#archives").delegate(".hasPosts","click",function(){var g=(b+1).toString();window.location.href="/archives/"+(g.length<2?"0"+g:g)+"/"+c+"/"})};
dx.comments=function(){var a=0,b=0,c=function(d){if(d=$(d.target).attr("rel")){var e=d*30,k=e+30-1;$(".comment").show();$(".comment:gt("+k+")").hide();$(".comment:lt("+e+")").hide();$(".commentPages .selected").removeClass("selected");$('.commentPages [rel="'+d+'"]').addClass("selected")}};$(".commentReply").click(function(d){d=$(d.target).parent().find(".user").text();$("#commentBody").val("@"+d).focus()});(function(){a=$(".commentReply").length;if(a>30){b=Math.ceil(a/30);$(".comment:gt(29)").hide();
var d='<ul class="commentPages">',e;for(e=0;e<b;e++)d+='<li><a href="#comments" class="commentPage'+(e===0?" selected":"")+'" rel="'+e+'">'+(e+1)+"</a></li>";d+="</ul>";$("#comments").append(d);$(d).insertAfter("#comments h3");$(".commentPage").click(c)}})()};
dx.gallery=function(){var a=function(c){c.preventDefault();var d=$(c.target).attr("href");d||(d=$(c.target).parents("a:first").attr("href"));d=d.match(/entry\/(.*?)\//)[1];$("#galleryBg").fadeIn(400,function(){var e=d;$("#galleryItem").prepend('<iframe src="/gallery/'+e+'/" id="galleryItem" frameborder="0"></iframe>')});$("#galleryItem").show().animate({width:"800px"})},b=function(){$("#galleryBg").fadeOut();$("#galleryItem").animate({width:0}).fadeOut();$("#galleryItem iframe").remove()};$(function(){$("#gallery a").click(a);
$("#galleryBg").detach().appendTo("body").click(b);$("#galleryItem").css("margin-top",($(window).height()-$("#galleryItem").height())/2+"px");$("#galleryItem .close").click(b)})};
(function(){var a=function(){var b=false;$("label.error").removeClass("error");if($("#commentName").length&&!$("#commentName").val()){b=true;$('label[for="commentName"]').addClass("error")}if($("#commentEmail").length&&!$("#commentEmail").val()){b=true;$('label[for="commentEmail"]').addClass("error")}else if($("#commentEmail").length){var c=$("#commentEmail").val();if(c.match(/([\w\d]+)@([\w\d]+)\.([\w])/))$("#botProof").val(hex_md5(c));else b=true}if(!$("#commentBody").val()){b=true;$('label[for="commentBody"]').addClass("error")}return!b};
$(function(){$("#commentForm").submit(a)})})();(function(a){a.fn.video=function(b){this.each(function(){a(this).append('<embed width="610" height="350" src="/global/flash/jcplayer.swf" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" align="middle" play="true" loop="true" scale="noScale" wmode="window" devicefont="false" bgcolor="#ffffff" name="jcplayer" menu="true" allowfullscreen="true" salign="TL" allowscriptaccess="sameDomain" flashvars="videoURL='+b+'&amp;autoHide=true&amp;margins=10&amp;offsetY=35&amp;highlightColor=0xf26716" type="application/x-shockwave-flash" />')})}})(jQuery);
(function(a){a.fn.youtube=function(b){this.each(function(){a(this).append('<embed width="540" height="304" src="http://www.youtube.com/v/'+b+"?enablejsapi=1&playerapiid="+a(this).attr("id")+'" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" align="middle" wmode="window" llowscriptaccess="sameDomain" type="application/x-shockwave-flash" />')})}})(jQuery);
(function(a){var b=function(c){var d=a('#search input[type="text"]').val();if(d.length>0)window.location="/search/"+d+"/";c.preventDefault()};a(function(){a("#search form").submit(b)})})(jQuery);$(function(){$(".gallery a").length>0&&$(".gallery a").lightBox()});